language: node_js
node_js:
- stable
script:
- make lint
before_deploy:
- make build
deploy:
  provider: firebase
  token:
    secure: rm/GJIK2bQW1nPQCQ2II71mre/soAw2XGAmPRrBUJJ16Z80iCuLSfAlXnuYXBV2Q3ssJBOnMUaOWaouLGLNn+j0klsnjC/SKSMscGBj+PvjbD0nxWi1R8+03MYp3C4wPZbPcdr0wOsNUdo5pNkwjFQBDqwLd4rSh0FltNQy7Xzpt7FbbMw1nvwpfvPOsy/TJGCdi7U0J8NX7fxbXQL+GMDAWSyYpy47ARXrDsYTkf1MlMBFcCWB+ke+8geBZfYjxLs3Ys7N0Q/H3RT1D4e1sPjSDVC1X/xU6OlS510R+jD6jJBe7l91lrriemf6uiDekVfnfYOC1Z6Axv6uN+2XQwdlTH2BshNqVSKognTLxa2IzOuGWjcA+ETjZFmsTpdyAHFDDbBHX0xqGyPYvbX3RgOZ1pldccB4kUZUfqrz5iY3QQemG53UYVzqHIF+VVB4cOwPfbwE6ejeLZhfOSSOgEIJtuXuX49JJPsazXmt1r7VIvY/tb6OJFkFRZZk2kp7/TOH7oWDb7xP7BYyqgKBczQfMd9BWtJ6oqcFeHjdyXrCQYoMYCSFJIj5icdAEkLx/XApUwsCjmGQ5/JaxRmmvgumUiN4DOqzq1Tx3i6v/UEmnA7X+Ubd9Z0dNKzLmsNUjskCIE5HpiIFKAOpCZq+ksmhS+GgY/Ybp2LP1UAzi+Ys=
