version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
