export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SIGNOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const SIGNOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const SIGNOUT_FAILED = 'LOGOUT_FAILED';

export const SIGNIN_REQUESTED = 'SIGNIN_REQUESTED';
export const SIGNIN_SUCCEEDED = 'SIGNIN_SUCCEEDED';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_SUCCEEDED = 'SIGNUP_SUCCEEDED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const ADD_ENTRY_REQUESTED = 'ADD_ENTRY_REQUESTED';
export const ADD_ENTRY_SUCCEEDED = 'ADD_ENTRY_SUCCEEDED';
export const ADD_ENTRY_FAILED = 'ADD_ENTRY_FAILED';

export const TIMELOG_FETCH_REQUESTED = 'TIMELOG_FETCH_REQUESTED';
export const TIMELOG_FETCH_SUCCEEDED = 'TIMELOG_FETCH_SUCCEEDED';
export const TIMELOG_FETCH_FAILED = 'TIMELOG_FETCH_FAILED';
